//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	corev1 "acme.corp/pkg/apis/core/v1"
)

// PodTemplateClusterLister can list PodTemplates across all workspaces, or scope down to a PodTemplateLister for one workspace.
// All objects returned here must be treated as read-only.
type PodTemplateClusterLister interface {
	// List lists all PodTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1.PodTemplate, err error)
	// Cluster returns a lister that can list and get PodTemplates in one workspace.
	Cluster(clusterName logicalcluster.Name) PodTemplateLister
	PodTemplateClusterListerExpansion
}

type podTemplateClusterLister struct {
	indexer cache.Indexer
}

// NewPodTemplateClusterLister returns a new PodTemplateClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewPodTemplateClusterLister(indexer cache.Indexer) *podTemplateClusterLister {
	return &podTemplateClusterLister{indexer: indexer}
}

// List lists all PodTemplates in the indexer across all workspaces.
func (s *podTemplateClusterLister) List(selector labels.Selector) (ret []*corev1.PodTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*corev1.PodTemplate))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get PodTemplates.
func (s *podTemplateClusterLister) Cluster(clusterName logicalcluster.Name) PodTemplateLister {
	return &podTemplateLister{indexer: s.indexer, clusterName: clusterName}
}

// PodTemplateLister can list PodTemplates across all namespaces, or scope down to a PodTemplateNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type PodTemplateLister interface {
	// List lists all PodTemplates in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1.PodTemplate, err error)
	// PodTemplates returns a lister that can list and get PodTemplates in one workspace and namespace.
	PodTemplates(namespace string) PodTemplateNamespaceLister
	PodTemplateListerExpansion
}

// podTemplateLister can list all PodTemplates inside a workspace or scope down to a PodTemplateLister for one namespace.
type podTemplateLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all PodTemplates in the indexer for a workspace.
func (s *podTemplateLister) List(selector labels.Selector) (ret []*corev1.PodTemplate, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*corev1.PodTemplate))
	})
	return ret, err
}

// PodTemplates returns an object that can list and get PodTemplates in one namespace.
func (s *podTemplateLister) PodTemplates(namespace string) PodTemplateNamespaceLister {
	return &podTemplateNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// podTemplateNamespaceLister helps list and get PodTemplates.
// All objects returned here must be treated as read-only.
type PodTemplateNamespaceLister interface {
	// List lists all PodTemplates in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corev1.PodTemplate, err error)
	// Get retrieves the PodTemplate from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corev1.PodTemplate, error)
	PodTemplateNamespaceListerExpansion
}

// podTemplateNamespaceLister helps list and get PodTemplates.
// All objects returned here must be treated as read-only.
type podTemplateNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all PodTemplates in the indexer for a given workspace and namespace.
func (s *podTemplateNamespaceLister) List(selector labels.Selector) (ret []*corev1.PodTemplate, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*corev1.PodTemplate))
	})
	return ret, err
}

// Get retrieves the PodTemplate from the indexer for a given workspace, namespace and name.
func (s *podTemplateNamespaceLister) Get(name string) (*corev1.PodTemplate, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(corev1.Resource("podtemplates"), name)
	}
	return obj.(*corev1.PodTemplate), nil
}

// NewPodTemplateLister returns a new PodTemplateLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewPodTemplateLister(indexer cache.Indexer) *podTemplateScopedLister {
	return &podTemplateScopedLister{indexer: indexer}
}

// podTemplateScopedLister can list all PodTemplates inside a workspace or scope down to a PodTemplateLister for one namespace.
type podTemplateScopedLister struct {
	indexer cache.Indexer
}

// List lists all PodTemplates in the indexer for a workspace.
func (s *podTemplateScopedLister) List(selector labels.Selector) (ret []*corev1.PodTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*corev1.PodTemplate))
	})
	return ret, err
}

// PodTemplates returns an object that can list and get PodTemplates in one namespace.
func (s *podTemplateScopedLister) PodTemplates(namespace string) PodTemplateNamespaceLister {
	return &podTemplateScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// podTemplateScopedNamespaceLister helps list and get PodTemplates.
type podTemplateScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all PodTemplates in the indexer for a given workspace and namespace.
func (s *podTemplateScopedNamespaceLister) List(selector labels.Selector) (ret []*corev1.PodTemplate, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*corev1.PodTemplate))
	})
	return ret, err
}

// Get retrieves the PodTemplate from the indexer for a given workspace, namespace and name.
func (s *podTemplateScopedNamespaceLister) Get(name string) (*corev1.PodTemplate, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(corev1.Resource("podtemplates"), name)
	}
	return obj.(*corev1.PodTemplate), nil
}
