/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"
	batchv1 "k8s.io/api/batch/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	upstreambatchv1client "k8s.io/client-go/kubernetes/typed/batch/v1"
)

// CronJobsClusterGetter has a method to return a CronJobClusterInterface.
// A group's client should implement this interface.
type CronJobsClusterGetter interface {
	CronJobs() CronJobClusterInterface
}

// CronJobClusterInterface has methods to work with CronJob resources.
type CronJobClusterInterface interface {
	List(ctx context.Context, opts v1.ListOptions) (*batchv1.CronJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Cluster(logicalcluster.Path) CronJobNamespacer
	CronJobExpansion
}

type cronJobsClusterInterface struct {
	clientCache kcpclient.Cache[*upstreambatchv1client.BatchV1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *cronJobsClusterInterface) Cluster(clusterPath logicalcluster.Path) CronJobNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &cronJobsNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all CronJobs that are available in all clusters.
func (c *cronJobsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*batchv1.CronJobList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).CronJobs(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all CronJobs across all clusters.
func (c *cronJobsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).CronJobs(metav1.NamespaceAll).Watch(ctx, opts)
}

// CronJobNamespacer can scope to objects within a namespace, returning a CronJobInterface.
type CronJobNamespacer interface {
	Namespace(name string) upstreambatchv1client.CronJobInterface
}

type cronJobsNamespacer struct {
	clientCache kcpclient.Cache[*upstreambatchv1client.BatchV1Client]
	clusterPath logicalcluster.Path
}

func (n *cronJobsNamespacer) Namespace(namespace string) upstreambatchv1client.CronJobInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).CronJobs(namespace)
}
