/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"
	v1alpha1 "k8s.io/api/networking/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	upstreamnetworkingv1alpha1client "k8s.io/client-go/kubernetes/typed/networking/v1alpha1"
)

// ServiceCIDRsClusterGetter has a method to return a ServiceCIDRClusterInterface.
// A group's client should implement this interface.
type ServiceCIDRsClusterGetter interface {
	ServiceCIDRs() ServiceCIDRClusterInterface
}

// ServiceCIDRClusterInterface has methods to work with ServiceCIDR resources.
type ServiceCIDRClusterInterface interface {
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ServiceCIDRList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Cluster(logicalcluster.Path) upstreamnetworkingv1alpha1client.ServiceCIDRInterface
	ServiceCIDRExpansion
}

type serviceCIDRsClusterInterface struct {
	clientCache kcpclient.Cache[*upstreamnetworkingv1alpha1client.NetworkingV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *serviceCIDRsClusterInterface) Cluster(clusterPath logicalcluster.Path) upstreamnetworkingv1alpha1client.ServiceCIDRInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).ServiceCIDRs()
}

// List returns the entire collection of all ServiceCIDRs that are available in all clusters.
func (c *serviceCIDRsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*v1alpha1.ServiceCIDRList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ServiceCIDRs().List(ctx, opts)
}

// Watch begins to watch all ServiceCIDRs across all clusters.
func (c *serviceCIDRsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ServiceCIDRs().Watch(ctx, opts)
}
