
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code auto-generated. DO NOT EDIT.

package v1



import (
	examplev1 "github.com/kcp-dev/code-generator/examples/pkg/apis/example/v1"
	"github.com/kcp-dev/logicalcluster"
	"k8s.io/client-go/tools/cache"
	"k8s.io/apimachinery/pkg/labels"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
)



// TestTypeLister helps list testType.
// All objects returned here must be treated as read-only.
type TestTypeLister interface {
	// List lists all testType in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*examplev1.TestType, err error)

	// Cluster returns an object that can list and get testType from the given logical cluster.
	Cluster(cluster logicalcluster.Name) TestTypeClusterLister

	// Note(kcp): Workspace-capable Lister implementation doesn't support support expansions.
	// TestTypeListerExpansion
}

// testTypeLister implements the TestTypeLister interface.
type testTypeLister struct {
	indexer cache.Indexer
}

// NewTestTypeLister returns a new TestTypeLister.
func NewTestTypeLister(indexer cache.Indexer) TestTypeLister {
	return &testTypeLister{indexer: indexer}
}

// List lists all testType in the indexer.
func (s *testTypeLister) List(selector labels.Selector) (ret []*examplev1.TestType, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*examplev1.TestType))
	})
	return ret, err
}

// Cluster returns an object that can list and get testType.
func (s *testTypeLister) Cluster(cluster logicalcluster.Name) TestTypeClusterLister {
	return &testTypeClusterLister{indexer: s.indexer, cluster: cluster}
}

// TestTypeLister helps list testType.
// All objects returned here must be treated as read-only.
type TestTypeClusterLister interface {
	// List lists all testType in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*examplev1.TestType, err error)
	// testType returns an object that can list and get testType.
	testType(namespace string) TestTypeNamespaceLister
	// Note(kcp): Workspace-capable Lister implementation doesn't support support expansions.
	// TestTypeListerExpansion
}

// testTypeClusterLister implements the TestTypeLister interface.
type testTypeClusterLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all testType in the indexer.
func (c *testTypeClusterLister) List(selector labels.Selector) (ret []*examplev1.TestType, err error) {
	list, err := c.indexer.ByIndex(ClusterIndexName, c.cluster.String())
	if err != nil {
		return nil, err
	}

	if selector == nil {
		selector = labels.Everything()
	}
	for i := range list {
		obj := list[i].(*examplev1.TestType)
		if selector.Matches(labels.Set(obj.GetLabels())) {
			ret = append(ret, obj)
		}
	}

	return ret, err
}

// testType returns an object that can list and get testType.
func (c *testTypeClusterLister) testType(namespace string) TestTypeNamespaceLister {
	return testTypeNamespaceLister{indexer: c.indexer, cluster: c.cluster, namespace: namespace}
}

// ConfigMapNamespaceLister helps list and get testType.
// All objects returned here must be treated as read-only.
type ConfigMapNamespaceLister interface {
	// List lists all testType in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*examplev1.TestType, err error)
	// Get retrieves the ConfigMap from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*examplev1.TestType, error)
	// Note(kcp): Workspace-capable Lister implementation doesn't support support expansions.
	// ConfigMapNamespaceListerExpansion
}

// testTypeNamespaceLister implements the ConfigMapNamespaceLister
// interface.
type testTypeNamespaceLister struct {
	indexer   cache.Indexer
	cluster   logicalcluster.Name
	namespace string
}

// List lists all testType in the indexer for a given namespace.
func (c testTypeNamespaceLister) List(selector labels.Selector) (ret []*examplev1.TestType, err error) {
	list, err := c.indexer.Index(ClusterAndNamespaceIndexName, &metav1.ObjectMeta{
		ZZZ_DeprecatedClusterName: c.cluster.String(),
		Namespace:                 c.namespace,
	})
	if err != nil {
		return nil, err
	}

	if selector == nil {
		selector = labels.Everything()
	}
	for i := range list {
		cm := list[i].(*examplev1.TestType)
		if selector.Matches(labels.Set(cm.GetLabels())) {
			ret = append(ret, cm)
		}
	}

	return ret, err
}

// Get retrieves the ConfigMap from the indexer for a given namespace and name.
func (c testTypeNamespaceLister) Get(name string) (*examplev1.TestType, error) {
	meta := &metav1.ObjectMeta{
		ZZZ_DeprecatedClusterName: c.cluster.String(),
		Namespace:                 c.namespace,
		Name:                      name,
	}
	obj, exists, err := c.indexer.Get(meta)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(examplev1.Resource("testType"), name)
	}
	return obj.(*examplev1.TestType), nil
}
