/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	upstreamimagepolicyv1alpha1client "k8s.io/client-go/kubernetes/typed/imagepolicy/v1alpha1"
)

// ImageReviewsClusterGetter has a method to return a ImageReviewClusterInterface.
// A group's client should implement this interface.
type ImageReviewsClusterGetter interface {
	ImageReviews() ImageReviewClusterInterface
}

// ImageReviewClusterInterface has methods to work with ImageReview resources.
type ImageReviewClusterInterface interface {
	ImageReviewExpansion
}

type imageReviewsClusterInterface struct {
	clientCache kcpclient.Cache[*upstreamimagepolicyv1alpha1client.ImagepolicyV1alpha1Client]
}
