/*
Copyright 2022 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package listergen

const apiWrapper = `
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package {{.Version}}

{{$typepkg := (printf "%s%s" .PkgName .Version)}}

import (
	{{ $typepkg }} "{{.APIPath}}"
	"github.com/kcp-dev/logicalcluster"
	"k8s.io/client-go/tools/cache"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/api/errors"
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
)

{{$fqkind := (printf "%s.%s" $typepkg .Name)}}

// {{.Name}}Lister helps list {{$fqkind}}.
// All objects returned here must be treated as read-only.
type {{.Name}}ClusterLister interface {
	// List lists all {{$fqkind}} in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*{{$fqkind}}, err error)

	// Cluster returns an object that can list and get {{$fqkind}} from the given logical cluster.
	Cluster(cluster logicalcluster.Name) {{.Name}}Lister
}

// {{lowerFirst .Name}}ClusterLister implements the {{.Name}}ClusterLister interface.
type {{lowerFirst .Name}}ClusterLister struct {
	indexer cache.Indexer
}

// New{{.Name}}ClusterLister returns a new {{.Name}}ClusterLister.
func New{{.Name}}ClusterLister(indexer cache.Indexer) {{.Name}}ClusterLister {
	return &{{lowerFirst .Name}}ClusterLister{indexer: indexer}
}

// List lists all {{$fqkind}} in the indexer.
func (s *{{lowerFirst .Name}}ClusterLister) List(selector labels.Selector) (ret []*{{$fqkind}}, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*{{$fqkind}}))
	})
	return ret, err
}

// Cluster returns an object that can list and get {{$fqkind}}.
func (s *{{lowerFirst .Name}}ClusterLister) Cluster(cluster logicalcluster.Name) {{.Name}}Lister {
	return &{{lowerFirst .Name}}Lister{indexer: s.indexer, cluster: cluster}
}

// {{.Name}}Lister helps list {{$fqkind}}.
// All objects returned here must be treated as read-only.
type {{.Name}}Lister interface {
	// List lists all {{$fqkind}} in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*{{$fqkind}}, err error)
	{{ if .IsNamespaced -}}
	// {{.Name}}s returns an object that can list and get {{$fqkind}}.
	{{.Name}}s(namespace string) {{.Name}}NamespaceLister
	{{ else -}}
	// Get retrieves the {{$fqkind}} from the indexer for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*{{$fqkind}}, error)
	{{ end -}}
}

// {{lowerFirst .Name}}Lister implements the {{.Name}}Lister interface.
type {{lowerFirst .Name}}Lister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all {{$fqkind}} in the indexer.
func (s *{{lowerFirst .Name}}Lister) List(selector labels.Selector) (ret []*{{$fqkind}}, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*{{$fqkind}})
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

{{ if  not .IsNamespaced -}}
// Get retrieves the {{$fqkind}} from the indexer for a given name.
func (s {{lowerFirst .Name}}Lister) Get(name string) (*{{$fqkind}}, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound({{$typepkg}}.Resource("{{lowerFirst .Name}}"), name)
	}
	return obj.(*{{$fqkind}}), nil
}
{{ else -}}
// {{.Name}}s returns an object that can list and get {{$fqkind}}.
func (s *{{lowerFirst .Name}}Lister) {{.Name}}s(namespace string) {{.Name}}NamespaceLister {
	return {{lowerFirst .Name}}NamespaceLister{indexer: s.indexer, cluster: s.cluster, namespace: namespace}
}

// {{.Name}}NamespaceLister helps list and get {{$fqkind}}.
// All objects returned here must be treated as read-only.
type {{.Name}}NamespaceLister interface {
	// List lists all {{$fqkind}} in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*{{$fqkind}}, err error)
	// Get retrieves the {{$fqkind}} from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*{{$fqkind}}, error)
}

// {{lowerFirst .Name}}NamespaceLister implements the {{.Name}}NamespaceLister interface.
type {{lowerFirst .Name}}NamespaceLister struct {
	indexer   cache.Indexer
	cluster   logicalcluster.Name
	namespace string
}

// List lists all {{$fqkind}} in the indexer for a given namespace.
func (s {{lowerFirst .Name}}NamespaceLister) List(selector labels.Selector) (ret []*{{$fqkind}}, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), s.namespace, "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterAndNamespaceIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*{{$fqkind}})
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}
	return ret, err
}

// Get retrieves the {{$fqkind}} from the indexer for a given namespace and name.
func (s {{lowerFirst .Name}}NamespaceLister) Get(name string) (*{{$fqkind}}, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound({{$typepkg}}.Resource("{{lowerFirst .Name}}"), name)
	}
	return obj.(*{{$fqkind}}), nil
}
{{ end -}}
`
