//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha3

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	resourcev1alpha3 "acme.corp/pkg/apis/resource/v1alpha3"
)

// ResourceClaimClusterLister can list ResourceClaims across all workspaces, or scope down to a ResourceClaimLister for one workspace.
// All objects returned here must be treated as read-only.
type ResourceClaimClusterLister interface {
	// List lists all ResourceClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceClaim, err error)
	// Cluster returns a lister that can list and get ResourceClaims in one workspace.
	Cluster(clusterName logicalcluster.Name) ResourceClaimLister
	ResourceClaimClusterListerExpansion
}

type resourceClaimClusterLister struct {
	indexer cache.Indexer
}

// NewResourceClaimClusterLister returns a new ResourceClaimClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewResourceClaimClusterLister(indexer cache.Indexer) *resourceClaimClusterLister {
	return &resourceClaimClusterLister{indexer: indexer}
}

// List lists all ResourceClaims in the indexer across all workspaces.
func (s *resourceClaimClusterLister) List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceClaim, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*resourcev1alpha3.ResourceClaim))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get ResourceClaims.
func (s *resourceClaimClusterLister) Cluster(clusterName logicalcluster.Name) ResourceClaimLister {
	return &resourceClaimLister{indexer: s.indexer, clusterName: clusterName}
}

// ResourceClaimLister can list ResourceClaims across all namespaces, or scope down to a ResourceClaimNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type ResourceClaimLister interface {
	// List lists all ResourceClaims in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceClaim, err error)
	// ResourceClaims returns a lister that can list and get ResourceClaims in one workspace and namespace.
	ResourceClaims(namespace string) ResourceClaimNamespaceLister
	ResourceClaimListerExpansion
}

// resourceClaimLister can list all ResourceClaims inside a workspace or scope down to a ResourceClaimLister for one namespace.
type resourceClaimLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all ResourceClaims in the indexer for a workspace.
func (s *resourceClaimLister) List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceClaim, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*resourcev1alpha3.ResourceClaim))
	})
	return ret, err
}

// ResourceClaims returns an object that can list and get ResourceClaims in one namespace.
func (s *resourceClaimLister) ResourceClaims(namespace string) ResourceClaimNamespaceLister {
	return &resourceClaimNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// resourceClaimNamespaceLister helps list and get ResourceClaims.
// All objects returned here must be treated as read-only.
type ResourceClaimNamespaceLister interface {
	// List lists all ResourceClaims in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceClaim, err error)
	// Get retrieves the ResourceClaim from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*resourcev1alpha3.ResourceClaim, error)
	ResourceClaimNamespaceListerExpansion
}

// resourceClaimNamespaceLister helps list and get ResourceClaims.
// All objects returned here must be treated as read-only.
type resourceClaimNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all ResourceClaims in the indexer for a given workspace and namespace.
func (s *resourceClaimNamespaceLister) List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceClaim, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*resourcev1alpha3.ResourceClaim))
	})
	return ret, err
}

// Get retrieves the ResourceClaim from the indexer for a given workspace, namespace and name.
func (s *resourceClaimNamespaceLister) Get(name string) (*resourcev1alpha3.ResourceClaim, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(resourcev1alpha3.Resource("resourceclaims"), name)
	}
	return obj.(*resourcev1alpha3.ResourceClaim), nil
}

// NewResourceClaimLister returns a new ResourceClaimLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewResourceClaimLister(indexer cache.Indexer) *resourceClaimScopedLister {
	return &resourceClaimScopedLister{indexer: indexer}
}

// resourceClaimScopedLister can list all ResourceClaims inside a workspace or scope down to a ResourceClaimLister for one namespace.
type resourceClaimScopedLister struct {
	indexer cache.Indexer
}

// List lists all ResourceClaims in the indexer for a workspace.
func (s *resourceClaimScopedLister) List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceClaim, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*resourcev1alpha3.ResourceClaim))
	})
	return ret, err
}

// ResourceClaims returns an object that can list and get ResourceClaims in one namespace.
func (s *resourceClaimScopedLister) ResourceClaims(namespace string) ResourceClaimNamespaceLister {
	return &resourceClaimScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// resourceClaimScopedNamespaceLister helps list and get ResourceClaims.
type resourceClaimScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ResourceClaims in the indexer for a given workspace and namespace.
func (s *resourceClaimScopedNamespaceLister) List(selector labels.Selector) (ret []*resourcev1alpha3.ResourceClaim, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*resourcev1alpha3.ResourceClaim))
	})
	return ret, err
}

// Get retrieves the ResourceClaim from the indexer for a given workspace, namespace and name.
func (s *resourceClaimScopedNamespaceLister) Get(name string) (*resourcev1alpha3.ResourceClaim, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(resourcev1alpha3.Resource("resourceclaims"), name)
	}
	return obj.(*resourcev1alpha3.ResourceClaim), nil
}
