//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	"net/http"

	kcpclient "github.com/kcp-dev/apimachinery/pkg/client"
	"github.com/kcp-dev/logicalcluster/v2"

	"k8s.io/client-go/rest"

	example3v1 "acme.corp/pkg/generated/clientset/versioned/typed/example3/v1"
)

type Example3V1ClusterInterface interface {
	Example3V1ClusterScoper
	TestTypesClusterGetter
	ClusterTestTypesClusterGetter
}

type Example3V1ClusterScoper interface {
	Cluster(logicalcluster.Name) example3v1.Example3V1Interface
}

type Example3V1ClusterClient struct {
	clientCache kcpclient.Cache[*example3v1.Example3V1Client]
}

func (c *Example3V1ClusterClient) Cluster(name logicalcluster.Name) example3v1.Example3V1Interface {
	if name == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}
	return c.clientCache.ClusterOrDie(name)
}

func (c *Example3V1ClusterClient) TestTypes() TestTypesClusterInterface {
	return &testTypesClusterInterface{clientCache: c.clientCache}
}

func (c *Example3V1ClusterClient) ClusterTestTypes() ClusterTestTypesClusterInterface {
	return &clusterTestTypesClusterInterface{clientCache: c.clientCache}
}

// NewForConfig creates a new Example3V1ClusterClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*Example3V1ClusterClient, error) {
	client, err := rest.HTTPClientFor(c)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(c, client)
}

// NewForConfigAndClient creates a new Example3V1ClusterClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*Example3V1ClusterClient, error) {
	cache := kcpclient.NewCache(c, h, &kcpclient.Constructor[*example3v1.Example3V1Client]{
		NewForConfigAndClient: example3v1.NewForConfigAndClient,
	})
	if _, err := cache.Cluster(logicalcluster.New("root")); err != nil {
		return nil, err
	}
	return &Example3V1ClusterClient{clientCache: cache}, nil
}

// NewForConfigOrDie creates a new Example3V1ClusterClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Example3V1ClusterClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}
