/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"
	v1alpha1 "k8s.io/api/coordination/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	upstreamcoordinationv1alpha1client "k8s.io/client-go/kubernetes/typed/coordination/v1alpha1"
	"k8s.io/client-go/testing"
	coordinationv1alpha1 "k8s.io/code-generator/examples/upstream/applyconfiguration/coordination/v1alpha1"
	kcp "k8s.io/code-generator/examples/upstream/clientset/versioned/typed/coordination/v1alpha1"
)

var leasecandidatesResource = v1alpha1.SchemeGroupVersion.WithResource("leasecandidates")

var leasecandidatesKind = v1alpha1.SchemeGroupVersion.WithKind("LeaseCandidate")

// leaseCandidatesClusterClient implements leaseCandidateInterface
type leaseCandidatesClusterClient struct {
	*kcptesting.Fake
}

// Cluster scopes the client down to a particular cluster.
func (c *leaseCandidatesClusterClient) Cluster(clusterPath logicalcluster.Path) *kcp.LeaseCandidateNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &leaseCandidatesNamespacer{Fake: c.Fake, ClusterPath: clusterPath}
}

// List takes label and field selectors, and returns the list of LeaseCandidates that match those selectors.
func (c *leaseCandidatesClusterClient) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LeaseCandidateList, err error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(leasecandidatesResource, leasecandidatesKind, logicalcluster.Wildcard, metav1.NamespaceAll, opts), &v1alpha1.LeaseCandidateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LeaseCandidateList{ListMeta: obj.(*v1alpha1.LeaseCandidateList).ListMeta}
	for _, item := range obj.(*v1alpha1.LeaseCandidateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested leaseCandidates across all clusters.
func (c *leaseCandidatesClusterClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(leasecandidatesResource, logicalcluster.Wildcard, metav1.NamespaceAll, opts))
}

type leaseCandidatesNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *leaseCandidatesNamespacer) Namespace(namespace string) upstreamcoordinationv1alpha1client.LeaseCandidateInterface {
	return &configMapsClient{Fake: n.Fake, ClusterPath: n.ClusterPath, Namespace: namespace}
}

type leaseCandidatesClient struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
	Namespace   string
}

func (c *leaseCandidatesClient) Create(ctx context.Context, leaseCandidate *v1alpha1.LeaseCandidate, opts metav1.CreateOptions) (*v1alpha1.LeaseCandidate, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewCreateAction(leasecandidatesResource, c.ClusterPath, c.Namespace, leaseCandidate), &v1alpha1.LeaseCandidate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LeaseCandidate), err
}

func (c *leaseCandidatesClient) Update(ctx context.Context, leaseCandidate *v1alpha1.LeaseCandidate, opts metav1.CreateOptions) (*v1alpha1.LeaseCandidate, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateAction(leasecandidatesResource, c.ClusterPath, c.Namespace, leaseCandidate), &v1alpha1.LeaseCandidate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LeaseCandidate), err
}

func (c *leaseCandidatesClient) UpdateStatus(ctx context.Context, leaseCandidate *v1alpha1.LeaseCandidate, opts metav1.CreateOptions) (*v1alpha1.LeaseCandidate, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateSubresourceAction(leasecandidatesResource, c.ClusterPath, "status", c.Namespace, leaseCandidate), &v1alpha1.LeaseCandidate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LeaseCandidate), err
}

func (c *leaseCandidatesClient) Delete(ctx context.Context, name string, opts metav1.CreateOptions) error {
	_, err := c.Fake.Invokes(kcptesting.NewDeleteActionWithOptions(leasecandidatesResource, c.ClusterPath, c.Namespace, name, opts), &v1alpha1.LeaseCandidate{})
	return err
}

func (c *leaseCandidatesClient) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := kcptesting.NewDeleteCollectionAction(leasecandidatesResource, c.ClusterPath, c.Namespace, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LeaseCandidateList{})
	return err
}

func (c *leaseCandidatesClient) Get(ctx context.Context, name string, options metav1.GetOptions) (*v1alpha1.LeaseCandidate, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewGetAction(leasecandidatesResource, c.ClusterPath, c.Namespace, name), &v1alpha1.LeaseCandidate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LeaseCandidate), err
}

// List takes label and field selectors, and returns the list of v1alpha1.LeaseCandidate that match those selectors.
func (c *leaseCandidatesClient) List(ctx context.Context, opts metav1.ListOptions) (*v1alpha1.LeaseCandidateList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(leasecandidatesResource, leasecandidatesKind, c.ClusterPath, c.Namespace, opts), &v1alpha1.LeaseCandidateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LeaseCandidateList{ListMeta: obj.(*v1alpha1.LeaseCandidateList).ListMeta}
	for _, item := range obj.(*v1alpha1.LeaseCandidateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

func (c *leaseCandidatesClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(leasecandidatesResource, c.ClusterPath, c.Namespace, opts))
}

func (c *leaseCandidatesClient) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*v1alpha1.LeaseCandidate, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewPatchSubresourceAction(leasecandidatesResource, c.ClusterPath, c.Namespace, name, pt, data, subresources...), &v1alpha1.LeaseCandidate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LeaseCandidate), err
}

func (c *leaseCandidatesClient) Apply(ctx context.Context, applyConfiguration *coordinationv1alpha1.LeaseCandidateApplyConfiguration, opts metav1.ApplyOptions) (*v1alpha1.LeaseCandidate, error) {
	if applyConfiguration == nil {
		return nil, fmt.Errorf("applyConfiguration provided to Apply must not be nil")
	}
	data, err := json.Marshal(applyConfiguration)
	if err != nil {
		return nil, err
	}
	name := applyConfiguration.Name
	if name == nil {
		return nil, fmt.Errorf("applyConfiguration.Name must be provided to Apply")
	}
	obj, err := c.Fake.Invokes(kcptesting.NewPatchSubresourceAction(leasecandidatesResource, c.ClusterPath, c.Namespace, *name, types.ApplyPatchType, data), &v1alpha1.LeaseCandidate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LeaseCandidate), err
}
