//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package fake

import (
	"github.com/kcp-dev/logicalcluster/v3"

	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"k8s.io/client-go/rest"

	somegroup2v1 "acme.corp/pkg/generated/clientset/versioned/typed/somegroup2/v1"
	kcpsomegroup2v1 "acme.corp/pkg/kcp/clients/clientset/versioned/typed/somegroup2/v1"
)

var _ kcpsomegroup2v1.Somegroup2V1ClusterInterface = (*Somegroup2V1ClusterClient)(nil)

type Somegroup2V1ClusterClient struct {
	*kcptesting.Fake
}

func (c *Somegroup2V1ClusterClient) Cluster(clusterPath logicalcluster.Path) somegroup2v1.Somegroup2V1Interface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}
	return &Somegroup2V1Client{Fake: c.Fake, ClusterPath: clusterPath}
}

func (c *Somegroup2V1ClusterClient) TestTypes() kcpsomegroup2v1.TestTypeClusterInterface {
	return &testTypesClusterClient{Fake: c.Fake}
}

func (c *Somegroup2V1ClusterClient) ClusterTestTypes() kcpsomegroup2v1.ClusterTestTypeClusterInterface {
	return &clusterTestTypesClusterClient{Fake: c.Fake}
}

var _ somegroup2v1.Somegroup2V1Interface = (*Somegroup2V1Client)(nil)

type Somegroup2V1Client struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (c *Somegroup2V1Client) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (c *Somegroup2V1Client) TestTypes(namespace string) somegroup2v1.TestTypeInterface {
	return &testTypesClient{Fake: c.Fake, ClusterPath: c.ClusterPath, Namespace: namespace}
}

func (c *Somegroup2V1Client) ClusterTestTypes() somegroup2v1.ClusterTestTypeInterface {
	return &clusterTestTypesClient{Fake: c.Fake, ClusterPath: c.ClusterPath}
}
