/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"
	upstreamrbacv1beta1client "k8s.io/client-go/kubernetes/typed/rbac/v1beta1"
	rest "k8s.io/client-go/rest"
	v1beta1 "k8s.io/code-generator/examples/upstream/clientset/versioned/typed/rbac/v1beta1"
)

type RbacV1beta1ClusterClient struct {
	*kcptesting.Fake
}

func (c *RbacV1beta1ClusterClient) Cluster(clusterPath logicalcluster.Path) upstreamrbacv1beta1client.RbacV1beta1Interface {

	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}
	return &RbacV1beta1Client{Fake: c.Fake, ClusterPath: clusterPath}
}

func (c *RbacV1beta1ClusterClient) ClusterRoles() v1beta1.ClusterRoleClusterInterface {
	return &clusterRolesClusterClient{Fake: c.Fake}
}

func (c *RbacV1beta1ClusterClient) ClusterRoleBindings() v1beta1.ClusterRoleBindingClusterInterface {
	return &clusterRoleBindingsClusterClient{Fake: c.Fake}
}

func (c *RbacV1beta1ClusterClient) Roles(namespace string) v1beta1.RoleClusterInterface {
	return &rolesClusterClient{Fake: c.Fake}
}

func (c *RbacV1beta1ClusterClient) RoleBindings(namespace string) v1beta1.RoleBindingClusterInterface {
	return &roleBindingsClusterClient{Fake: c.Fake}
}

type RbacV1beta1Client struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *RbacV1beta1Client) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (c *RbacV1beta1Client) ClusterRoles() upstreamrbacv1beta1client.ClusterRoleInterface {

	return &clusterRolesClient{Fake: c.Fake, ClusterPath: c.ClusterPath}
}

func (c *RbacV1beta1Client) ClusterRoleBindings() upstreamrbacv1beta1client.ClusterRoleBindingInterface {

	return &clusterRoleBindingsClient{Fake: c.Fake, ClusterPath: c.ClusterPath}
}

func (c *RbacV1beta1Client) Roles(namespace string) upstreamrbacv1beta1client.RoleInterface {

	return &rolesClient{Fake: c.Fake, ClusterPath: c.ClusterPath, Namespace: namespace}
}

func (c *RbacV1beta1Client) RoleBindings(namespace string) upstreamrbacv1beta1client.RoleBindingInterface {

	return &roleBindingsClient{Fake: c.Fake, ClusterPath: c.ClusterPath, Namespace: namespace}
}
