/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"
	v1beta1 "k8s.io/api/authorization/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	upstreamauthorizationv1beta1client "k8s.io/client-go/kubernetes/typed/authorization/v1beta1"
	"k8s.io/client-go/testing"
	authorizationv1beta1 "k8s.io/code-generator/examples/upstream/applyconfiguration/authorization/v1beta1"
	kcp "k8s.io/code-generator/examples/upstream/clientset/versioned/typed/authorization/v1beta1"
)

var localsubjectaccessreviewsResource = v1beta1.SchemeGroupVersion.WithResource("localsubjectaccessreviews")

var localsubjectaccessreviewsKind = v1beta1.SchemeGroupVersion.WithKind("LocalSubjectAccessReview")

// localSubjectAccessReviewsClusterClient implements localSubjectAccessReviewInterface
type localSubjectAccessReviewsClusterClient struct {
	*kcptesting.Fake
}

// Cluster scopes the client down to a particular cluster.
func (c *localSubjectAccessReviewsClusterClient) Cluster(clusterPath logicalcluster.Path) *kcp.LocalSubjectAccessReviewNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &localSubjectAccessReviewsNamespacer{Fake: c.Fake, ClusterPath: clusterPath}
}

// List takes label and field selectors, and returns the list of LocalSubjectAccessReviews that match those selectors.
func (c *localSubjectAccessReviewsClusterClient) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.LocalSubjectAccessReviewList, err error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(localsubjectaccessreviewsResource, localsubjectaccessreviewsKind, logicalcluster.Wildcard, metav1.NamespaceAll, opts), &v1beta1.LocalSubjectAccessReviewList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.LocalSubjectAccessReviewList{ListMeta: obj.(*v1beta1.LocalSubjectAccessReviewList).ListMeta}
	for _, item := range obj.(*v1beta1.LocalSubjectAccessReviewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localSubjectAccessReviews across all clusters.
func (c *localSubjectAccessReviewsClusterClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(localsubjectaccessreviewsResource, logicalcluster.Wildcard, metav1.NamespaceAll, opts))
}

type localSubjectAccessReviewsNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *localSubjectAccessReviewsNamespacer) Namespace(namespace string) upstreamauthorizationv1beta1client.LocalSubjectAccessReviewInterface {
	return &configMapsClient{Fake: n.Fake, ClusterPath: n.ClusterPath, Namespace: namespace}
}

type localSubjectAccessReviewsClient struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
	Namespace   string
}

func (c *localSubjectAccessReviewsClient) Create(ctx context.Context, localSubjectAccessReview *v1beta1.LocalSubjectAccessReview, opts metav1.CreateOptions) (*v1beta1.LocalSubjectAccessReview, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewCreateAction(localsubjectaccessreviewsResource, c.ClusterPath, c.Namespace, localSubjectAccessReview), &v1beta1.LocalSubjectAccessReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LocalSubjectAccessReview), err
}

func (c *localSubjectAccessReviewsClient) Update(ctx context.Context, localSubjectAccessReview *v1beta1.LocalSubjectAccessReview, opts metav1.CreateOptions) (*v1beta1.LocalSubjectAccessReview, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateAction(localsubjectaccessreviewsResource, c.ClusterPath, c.Namespace, localSubjectAccessReview), &v1beta1.LocalSubjectAccessReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LocalSubjectAccessReview), err
}

func (c *localSubjectAccessReviewsClient) UpdateStatus(ctx context.Context, localSubjectAccessReview *v1beta1.LocalSubjectAccessReview, opts metav1.CreateOptions) (*v1beta1.LocalSubjectAccessReview, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewUpdateSubresourceAction(localsubjectaccessreviewsResource, c.ClusterPath, "status", c.Namespace, localSubjectAccessReview), &v1beta1.LocalSubjectAccessReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LocalSubjectAccessReview), err
}

func (c *localSubjectAccessReviewsClient) Delete(ctx context.Context, name string, opts metav1.CreateOptions) error {
	_, err := c.Fake.Invokes(kcptesting.NewDeleteActionWithOptions(localsubjectaccessreviewsResource, c.ClusterPath, c.Namespace, name, opts), &v1beta1.LocalSubjectAccessReview{})
	return err
}

func (c *localSubjectAccessReviewsClient) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := kcptesting.NewDeleteCollectionAction(localsubjectaccessreviewsResource, c.ClusterPath, c.Namespace, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.LocalSubjectAccessReviewList{})
	return err
}

func (c *localSubjectAccessReviewsClient) Get(ctx context.Context, name string, options metav1.GetOptions) (*v1beta1.LocalSubjectAccessReview, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewGetAction(localsubjectaccessreviewsResource, c.ClusterPath, c.Namespace, name), &v1beta1.LocalSubjectAccessReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LocalSubjectAccessReview), err
}

// List takes label and field selectors, and returns the list of v1beta1.LocalSubjectAccessReview that match those selectors.
func (c *localSubjectAccessReviewsClient) List(ctx context.Context, opts metav1.ListOptions) (*v1beta1.LocalSubjectAccessReviewList, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewListAction(localsubjectaccessreviewsResource, localsubjectaccessreviewsKind, c.ClusterPath, c.Namespace, opts), &v1beta1.LocalSubjectAccessReviewList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.LocalSubjectAccessReviewList{ListMeta: obj.(*v1beta1.LocalSubjectAccessReviewList).ListMeta}
	for _, item := range obj.(*v1beta1.LocalSubjectAccessReviewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

func (c *localSubjectAccessReviewsClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.InvokesWatch(kcptesting.NewWatchAction(localsubjectaccessreviewsResource, c.ClusterPath, c.Namespace, opts))
}

func (c *localSubjectAccessReviewsClient) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*v1beta1.LocalSubjectAccessReview, error) {
	obj, err := c.Fake.Invokes(kcptesting.NewPatchSubresourceAction(localsubjectaccessreviewsResource, c.ClusterPath, c.Namespace, name, pt, data, subresources...), &v1beta1.LocalSubjectAccessReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LocalSubjectAccessReview), err
}

func (c *localSubjectAccessReviewsClient) Apply(ctx context.Context, applyConfiguration *authorizationv1beta1.LocalSubjectAccessReviewApplyConfiguration, opts metav1.ApplyOptions) (*v1beta1.LocalSubjectAccessReview, error) {
	if applyConfiguration == nil {
		return nil, fmt.Errorf("applyConfiguration provided to Apply must not be nil")
	}
	data, err := json.Marshal(applyConfiguration)
	if err != nil {
		return nil, err
	}
	name := applyConfiguration.Name
	if name == nil {
		return nil, fmt.Errorf("applyConfiguration.Name must be provided to Apply")
	}
	obj, err := c.Fake.Invokes(kcptesting.NewPatchSubresourceAction(localsubjectaccessreviewsResource, c.ClusterPath, c.Namespace, *name, types.ApplyPatchType, data), &v1beta1.LocalSubjectAccessReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.LocalSubjectAccessReview), err
}
