/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"
	appsv1 "k8s.io/api/apps/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	upstreamappsv1client "k8s.io/client-go/kubernetes/typed/apps/v1"
)

// ControllerRevisionsClusterGetter has a method to return a ControllerRevisionClusterInterface.
// A group's client should implement this interface.
type ControllerRevisionsClusterGetter interface {
	ControllerRevisions() ControllerRevisionClusterInterface
}

// ControllerRevisionClusterInterface has methods to work with ControllerRevision resources.
type ControllerRevisionClusterInterface interface {
	List(ctx context.Context, opts v1.ListOptions) (*appsv1.ControllerRevisionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Cluster(logicalcluster.Path) ControllerRevisionNamespacer
	ControllerRevisionExpansion
}

type controllerRevisionsClusterInterface struct {
	clientCache kcpclient.Cache[*upstreamappsv1client.AppsV1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *controllerRevisionsClusterInterface) Cluster(clusterPath logicalcluster.Path) ControllerRevisionNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &controllerRevisionsNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all ControllerRevisions that are available in all clusters.
func (c *controllerRevisionsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*appsv1.ControllerRevisionList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ControllerRevisions(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all ControllerRevisions across all clusters.
func (c *controllerRevisionsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ControllerRevisions(metav1.NamespaceAll).Watch(ctx, opts)
}

// ControllerRevisionNamespacer can scope to objects within a namespace, returning a ControllerRevisionInterface.
type ControllerRevisionNamespacer interface {
	Namespace(name string) upstreamappsv1client.ControllerRevisionInterface
}

type controllerRevisionsNamespacer struct {
	clientCache kcpclient.Cache[*upstreamappsv1client.AppsV1Client]
	clusterPath logicalcluster.Path
}

func (n *controllerRevisionsNamespacer) Namespace(namespace string) upstreamappsv1client.ControllerRevisionInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).ControllerRevisions(namespace)
}
